spring.datasource.url=jdbc:postgresql://localhost:5432/logistics_db
spring.datasource.username=postgres
spring.datasource.password=1234

app.jwt.secret=LogisticsJwtSecretKeyForSpringBoot3Example_1234567890
app.jwt.expiration-ms=86400000
